name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2

      - name: Zig version
        run: zig version

      - name: Lint
        run: zig fmt --check .

      - name: Test
        run: zig build test
