name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: "0.10.1"

      - name: Download packages
        run: make tidy

      - name: Lint
        run: make lint

      - name: Test
        run: make test
